import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:munokolive_music/models/place_model.dart';
import 'package:munokolive_music/models/user_profile.dart';
import 'package:munokolive_music/providers/user_provider.dart';
import 'package:munokolive_music/services/place_service.dart';
import 'package:munokolive_music/ui/events/widgets/location_picker_widget.dart';
import 'package:munokolive_music/ui/theme/app_theme.dart';

class AddPlacePage extends ConsumerStatefulWidget {
  const AddPlacePage({super.key});

  @override
  ConsumerState<AddPlacePage> createState() => _AddPlacePageState();
}

class _AddPlacePageState extends ConsumerState<AddPlacePage> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _descController = TextEditingController();
  final _phoneController = TextEditingController();
  final _cityController = TextEditingController();
  final _communeController = TextEditingController();
  final _neighborhoodController = TextEditingController();

  PlaceCategory _selectedCategory = PlaceCategory.studio;
  GeoPoint? _selectedCoordinates;
  String? _pickedAddress;
  File? _selectedImage;
  bool _isSubmitting = false;

  @override
  void dispose() {
    _nameController.dispose();
    _descController.dispose();
    _phoneController.dispose();
    _cityController.dispose();
    _communeController.dispose();
    _neighborhoodController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(source: ImageSource.gallery);
    if (pickedFile != null) {
      setState(() {
        _selectedImage = File(pickedFile.path);
      });
    }
  }

  Future<void> _submitPlace(UserProfile user) async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedCoordinates == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Veuillez sélectionner une localisation sur la carte.'),
        ),
      );
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      // Mock Image Upload (In real app, upload to Firebase Storage)
      // For now, we use a placeholder if no image, or a local path (which won't work for other users but ok for demo)
      // Better: Use a random picsum image if no image uploaded, or simulate upload.
      String imageUrl =
          "https://picsum.photos/800/600?random=${DateTime.now().millisecondsSinceEpoch}";

      final place = PlaceModel(
        id: '', // Generated by Firestore
        name: _nameController.text.trim(),
        description: _descController.text.trim(),
        category: _selectedCategory,
        coordinates: _selectedCoordinates,
        address:
            _pickedAddress ??
            "${_neighborhoodController.text}, ${_communeController.text}",
        city: _cityController.text.trim(),
        commune: _communeController.text.trim(),
        neighborhood: _neighborhoodController.text.trim(),
        images: [imageUrl], // Only one image for now
        ownerId: user.uid,
        ownerName: "${user.firstName} ${user.lastName}",
        contactPhone: _phoneController.text.trim(),
        status: PlaceStatus.pending, // Default to Pending
        isVerified: false,
        createdAt: DateTime.now(),
        features: [], // Can add feature selector later
      );

      await ref.read(placeServiceProvider).addPlace(place);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text(
              'Lieu soumis avec succès ! Il sera visible après validation.',
            ),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erreur: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final userAsync = ref.watch(userProfileProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Ajouter un Lieu'),
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      extendBodyBehindAppBar: true,
      body: Container(
        decoration: const BoxDecoration(gradient: AppTheme.mainGradient),
        child: userAsync.when(
          data: (user) => user == null
              ? const Center(child: Text("Erreur utilisateur"))
              : SafeArea(
                  child: SingleChildScrollView(
                    padding: const EdgeInsets.all(16),
                    child: Form(
                      key: _formKey,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          _buildSectionTitle("1. Informations du Lieu"),
                          _buildTextField(
                            _nameController,
                            "Nom du lieu",
                            Icons.store,
                          ),
                          const SizedBox(height: 10),
                          _buildTextField(
                            _descController,
                            "Description courte",
                            Icons.description,
                            maxLines: 3,
                          ),
                          const SizedBox(height: 10),
                          _buildCategoryDropdown(),
                          const SizedBox(height: 20),

                          _buildSectionTitle("2. Localisation"),
                          LocationPickerWidget(
                            onLocationSelected: (point, address) {
                              setState(() {
                                _selectedCoordinates = point;
                                _pickedAddress = address;
                                // Try to parse address into city/commune if possible, or let user fill manually
                              });
                            },
                          ),
                          const SizedBox(height: 10),
                          Row(
                            children: [
                              Expanded(
                                child: _buildTextField(
                                  _cityController,
                                  "Ville",
                                  Icons.location_city,
                                ),
                              ),
                              const SizedBox(width: 10),
                              Expanded(
                                child: _buildTextField(
                                  _communeController,
                                  "Commune",
                                  Icons.map,
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 10),
                          _buildTextField(
                            _neighborhoodController,
                            "Quartier",
                            Icons.home_work,
                          ),
                          const SizedBox(height: 20),

                          _buildSectionTitle("3. Contact & Responsable"),
                          _buildReadOnlyField(
                            "Responsable",
                            "${user.firstName} ${user.lastName}",
                            Icons.person,
                          ),
                          const SizedBox(height: 10),
                          _buildTextField(
                            _phoneController,
                            "Téléphone (Contact direct)",
                            Icons.phone,
                            keyboardType: TextInputType.phone,
                          ),
                          const SizedBox(height: 20),

                          _buildSectionTitle("4. Photos"),
                          GestureDetector(
                            onTap: _pickImage,
                            child: Container(
                              height: 150,
                              decoration: BoxDecoration(
                                color: Colors.white.withValues(alpha: 0.1),
                                borderRadius: BorderRadius.circular(15),
                                border: Border.all(color: Colors.white30),
                                image: _selectedImage != null
                                    ? DecorationImage(
                                        image: FileImage(_selectedImage!),
                                        fit: BoxFit.cover,
                                      )
                                    : null,
                              ),
                              child: _selectedImage == null
                                  ? const Column(
                                      mainAxisAlignment:
                                          MainAxisAlignment.center,
                                      children: [
                                        Icon(
                                          Icons.add_a_photo,
                                          color: Colors.white70,
                                          size: 40,
                                        ),
                                        SizedBox(height: 8),
                                        Text(
                                          "Ajouter une photo de couverture",
                                          style: TextStyle(
                                            color: Colors.white70,
                                          ),
                                        ),
                                      ],
                                    )
                                  : null,
                            ),
                          ),
                          const SizedBox(height: 30),

                          ElevatedButton(
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppTheme.primaryColor,
                              padding: const EdgeInsets.symmetric(vertical: 16),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            onPressed: _isSubmitting
                                ? null
                                : () => _submitPlace(user),
                            child: _isSubmitting
                                ? const CircularProgressIndicator(
                                    color: Colors.white,
                                  )
                                : const Text(
                                    "SOUMETTRE POUR VALIDATION",
                                    style: TextStyle(
                                      fontSize: 16,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                          ),
                          const SizedBox(height: 20),
                        ],
                      ),
                    ),
                  ),
                ),
          loading: () => const Center(child: CircularProgressIndicator()),
          error: (e, s) => Center(
            child: Text(
              "Erreur: $e",
              style: const TextStyle(color: Colors.white),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Text(
        title,
        style: const TextStyle(
          color: AppTheme.primaryColor,
          fontSize: 18,
          fontWeight: FontWeight.bold,
        ),
      ),
    );
  }

  Widget _buildTextField(
    TextEditingController controller,
    String label,
    IconData icon, {
    int maxLines = 1,
    TextInputType? keyboardType,
  }) {
    return TextFormField(
      controller: controller,
      style: const TextStyle(color: Colors.white),
      maxLines: maxLines,
      keyboardType: keyboardType,
      validator: (val) => val == null || val.isEmpty ? 'Champ requis' : null,
      decoration: InputDecoration(
        labelText: label,
        labelStyle: const TextStyle(color: Colors.white70),
        prefixIcon: Icon(icon, color: AppTheme.primaryColor),
        filled: true,
        fillColor: Colors.white.withValues(alpha: 0.05),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: AppTheme.primaryColor),
        ),
      ),
    );
  }

  Widget _buildReadOnlyField(String label, String value, IconData icon) {
    return TextFormField(
      initialValue: value,
      readOnly: true,
      style: const TextStyle(color: Colors.white70),
      decoration: InputDecoration(
        labelText: label,
        labelStyle: const TextStyle(color: Colors.white70),
        prefixIcon: Icon(icon, color: Colors.grey),
        filled: true,
        fillColor: Colors.white.withValues(alpha: 0.05),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
      ),
    );
  }

  Widget _buildCategoryDropdown() {
    return DropdownButtonFormField<PlaceCategory>(
      initialValue: _selectedCategory,
      dropdownColor: AppTheme.backgroundDark,
      style: const TextStyle(color: Colors.white),
      decoration: InputDecoration(
        labelText: "Catégorie",
        labelStyle: const TextStyle(color: Colors.white70),
        prefixIcon: const Icon(Icons.category, color: AppTheme.primaryColor),
        filled: true,
        fillColor: Colors.white.withValues(alpha: 0.05),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
      ),
      items: PlaceCategory.values.map((cat) {
        String label = 'Autre';
        switch (cat) {
          case PlaceCategory.studio:
            label = 'Studio d\'enregistrement';
            break;
          case PlaceCategory.rehearsalRoom:
            label = 'Salle de répétition';
            break;
          case PlaceCategory.eventSpace:
            label = 'Espace événementiel';
            break;
          case PlaceCategory.trainingRoom:
            label = 'Salle de formation';
            break;
          case PlaceCategory.other:
            label = 'Autre';
            break;
        }
        return DropdownMenuItem(value: cat, child: Text(label));
      }).toList(),
      onChanged: (val) {
        if (val != null) setState(() => _selectedCategory = val);
      },
    );
  }
}
