// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpZooW2LNkX9a-JOODcOcmj8u6mPRSt8M',
    appId: '1:506078346532:web:31633ec871dfba1333c7b1',
    messagingSenderId: '506078346532',
    projectId: 'munokolivemusic2026',
    authDomain: 'munokolivemusic2026.firebaseapp.com',
    storageBucket: 'munokolivemusic2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDISU6Ilf3RJYb1rt5imGcl42m8l4gG6s',
    appId: '1:506078346532:android:6f0e95a11c03b62533c7b1',
    messagingSenderId: '506078346532',
    projectId: 'munokolivemusic2026',
    storageBucket: 'munokolivemusic2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7YGaymbvusBZ2TRC7013MPkYlzr5CbHo',
    appId: '1:506078346532:ios:d6660cad8a478a1a33c7b1',
    messagingSenderId: '506078346532',
    projectId: 'munokolivemusic2026',
    storageBucket: 'munokolivemusic2026.firebasestorage.app',
    iosClientId:
        '506078346532-o2hkunsp0eg7ne47er0g9jm0rp3tbkt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.munokoliveMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7YGaymbvusBZ2TRC7013MPkYlzr5CbHo',
    appId: '1:506078346532:ios:d6660cad8a478a1a33c7b1',
    messagingSenderId: '506078346532',
    projectId: 'munokolivemusic2026',
    storageBucket: 'munokolivemusic2026.firebasestorage.app',
    iosClientId:
        '506078346532-o2hkunsp0eg7ne47er0g9jm0rp3tbkt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.munokoliveMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpZooW2LNkX9a-JOODcOcmj8u6mPRSt8M',
    appId: '1:506078346532:web:c8d17af89a19900733c7b1',
    messagingSenderId: '506078346532',
    projectId: 'munokolivemusic2026',
    authDomain: 'munokolivemusic2026.firebaseapp.com',
    storageBucket: 'munokolivemusic2026.firebasestorage.app',
  );
}
