-- Security Hardening Migration
-- 2024-01-26
-- Implements: Zero Trust RLS, Admin Protection, Brute Force IP Blocking, Data Isolation

-- 1. IP Blocking & Brute Force Infrastructure
CREATE TABLE IF NOT EXISTS public.security_logs (
    id bigint generated by default as identity primary key,
    ip_address text not null,
    event_type text not null, -- 'failed_login', 'suspicious_activity'
    created_at timestamp with time zone default timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.blocked_ips (
    ip_address text primary key,
    blocked_until timestamp with time zone not null,
    reason text
);

-- Function to check if current IP is blocked
CREATE OR REPLACE FUNCTION public.is_ip_blocked()
RETURNS boolean AS $$
DECLARE
    current_ip text;
BEGIN
    -- Attempt to get IP from headers (works in Supabase environment)
    current_ip := current_setting('request.headers', true)::json->>'x-forwarded-for';
    
    IF current_ip IS NULL THEN
        RETURN false; -- Default to allow if IP unknown (local dev/edge cases)
    END IF;
    
    PERFORM 1 FROM public.blocked_ips 
    WHERE ip_address = current_ip 
    AND blocked_until > timezone('utc'::text, now());
    
    RETURN FOUND;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to record failed attempt (Called by App on login failure)
CREATE OR REPLACE FUNCTION public.record_failed_login()
RETURNS void AS $$
DECLARE
    user_ip text;
    recent_failures int;
BEGIN
    user_ip := current_setting('request.headers', true)::json->>'x-forwarded-for';
    
    IF user_ip IS NULL THEN
        RETURN;
    END IF;

    INSERT INTO public.security_logs (ip_address, event_type) VALUES (user_ip, 'failed_login');
    
    SELECT count(*) INTO recent_failures
    FROM public.security_logs
    WHERE ip_address = user_ip 
    AND event_type = 'failed_login'
    AND created_at > timezone('utc'::text, now()) - interval '1 minute';
    
    IF recent_failures >= 5 THEN
        INSERT INTO public.blocked_ips (ip_address, blocked_until, reason)
        VALUES (user_ip, timezone('utc'::text, now()) + interval '30 minutes', 'Brute force detection')
        ON CONFLICT (ip_address) 
        DO UPDATE SET blocked_until = timezone('utc'::text, now()) + interval '30 minutes';
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant access to anon (unauthenticated) so they can report their own failures
GRANT EXECUTE ON FUNCTION public.record_failed_login() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_ip_blocked() TO anon, authenticated, service_role;

-- 2. Secure Users Table
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Clean up existing permissive policies
DROP POLICY IF EXISTS "Enable read access for all users" ON public.users;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.users;
DROP POLICY IF EXISTS "Enable update for users based on email" ON public.users;
DROP POLICY IF EXISTS "Users can read own profile" ON public.users;
DROP POLICY IF EXISTS "Users can update own profile" ON public.users;
DROP POLICY IF EXISTS "Admin full access" ON public.users;
DROP POLICY IF EXISTS "Enable insert for registration" ON public.users;

-- Policy: Admin Full Access (Bypasses IP Block for safety)
CREATE POLICY "Admin full access"
ON public.users FOR ALL
USING (auth.jwt()->>'email' = 'munokolive@gmail.com');

-- Policy: Users can read ONLY their own profile (Strict Isolation)
CREATE POLICY "Users can read own profile"
ON public.users FOR SELECT
USING (
    (auth.uid() = id)
    AND NOT public.is_ip_blocked()
);

-- Policy: Users can update ONLY their own profile
CREATE POLICY "Users can update own profile"
ON public.users FOR UPDATE
USING (
    (auth.uid() = id)
    AND NOT public.is_ip_blocked()
);

-- Policy: Everyone can insert (Registration)
CREATE POLICY "Enable insert for registration"
ON public.users FOR INSERT
WITH CHECK (
    auth.uid() = id
    AND NOT public.is_ip_blocked()
);

-- 3. Protect 'is_validated' Column (Admin Only)
CREATE OR REPLACE FUNCTION public.protect_critical_columns()
RETURNS trigger AS $$
BEGIN
    -- Check if is_validated is being changed
    IF NEW.is_validated IS DISTINCT FROM OLD.is_validated THEN
        -- Allow if Admin
        IF auth.jwt()->>'email' = 'munokolive@gmail.com' THEN
            RETURN NEW;
        END IF;
        
        RAISE EXCEPTION 'Security Violation: Only Administrator can change validation status.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_protect_critical_columns ON public.users;
CREATE TRIGGER tr_protect_critical_columns
BEFORE UPDATE ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.protect_critical_columns();

-- 4. Messages Table (Strict Isolation)
CREATE TABLE IF NOT EXISTS public.messages (
    id bigint generated by default as identity primary key,
    sender_id uuid references auth.users(id) not null,
    receiver_id uuid references auth.users(id) not null,
    content text,
    is_read boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own messages" ON public.messages;
CREATE POLICY "Users can read own messages"
ON public.messages FOR SELECT
USING (
    (auth.uid() = sender_id OR auth.uid() = receiver_id)
    AND NOT public.is_ip_blocked()
);

DROP POLICY IF EXISTS "Users can send messages" ON public.messages;
CREATE POLICY "Users can send messages"
ON public.messages FOR INSERT
WITH CHECK (
    auth.uid() = sender_id
    AND NOT public.is_ip_blocked()
);

-- 5. Referrals Table (Strict Isolation)
CREATE TABLE IF NOT EXISTS public.referrals (
    id bigint generated by default as identity primary key,
    referrer_id uuid references auth.users(id) not null,
    referred_email text,
    status text default 'pending', -- pending, validated
    created_at timestamp with time zone default timezone('utc'::text, now())
);
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own referrals" ON public.referrals;
CREATE POLICY "Users can read own referrals"
ON public.referrals FOR SELECT
USING (
    auth.uid() = referrer_id
    AND NOT public.is_ip_blocked()
);

DROP POLICY IF EXISTS "Users can create referrals" ON public.referrals;
CREATE POLICY "Users can create referrals"
ON public.referrals FOR INSERT
WITH CHECK (
    auth.uid() = referrer_id
    AND NOT public.is_ip_blocked()
);
