-- Migration: Device Integrity Check Infrastructure
-- Created: 2024-01-27

-- 1. Table to log integrity checks
CREATE TABLE IF NOT EXISTS public.integrity_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id),
    platform text,
    token_preview text, -- Store first few chars for debugging
    is_valid boolean default false,
    error_message text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

ALTER TABLE public.integrity_logs ENABLE ROW LEVEL SECURITY;

-- Only admins can read logs
CREATE POLICY "Admins can view integrity logs"
ON public.integrity_logs FOR SELECT
USING (auth.jwt()->>'email' = 'munokolive@gmail.com');

-- 2. Function to Validated Integrity (Mock Implementation)
-- In production, this should call a Supabase Edge Function that communicates 
-- with Google Play Integrity API and Apple App Attest API.
CREATE OR REPLACE FUNCTION public.validate_device_integrity(
    p_token text,
    p_platform text
)
RETURNS boolean AS $$
DECLARE
    v_user_id uuid;
BEGIN
    v_user_id := auth.uid();
    
    -- MOCK VALIDATION: 
    -- Currently returns TRUE if token is not empty.
    -- TODO: Replace with actual Edge Function call or strict validation logic.
    -- Example: 
    -- perform net.http_post('https://project.supabase.co/functions/v1/verify-integrity', ...);
    
    IF p_token IS NULL OR length(p_token) < 10 THEN
        INSERT INTO public.integrity_logs (user_id, platform, token_preview, is_valid, error_message)
        VALUES (v_user_id, p_platform, 'INVALID_LENGTH', false, 'Token too short or null');
        RETURN false;
    END IF;

    -- Log successful check (mock)
    INSERT INTO public.integrity_logs (user_id, platform, token_preview, is_valid)
    VALUES (v_user_id, p_platform, substring(p_token from 1 for 20) || '...', true);

    RETURN true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute to authenticated users so they can verify themselves
GRANT EXECUTE ON FUNCTION public.validate_device_integrity(text, text) TO authenticated;
