create table if not exists public.app_config (
  id bigint generated by default as identity primary key,
  maintenance_mode boolean default false,
  radar_radius int default 5000,
  ai_message text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

insert into public.app_config (id, maintenance_mode, radar_radius)
values (1, false, 5000)
on conflict (id) do nothing;

alter table public.app_config enable row level security;

create policy "Enable read access for all users"
on public.app_config for select
using (true);

create policy "Enable update for admins"
on public.app_config for update
using (
  auth.uid() in (
    select id from public.users where role = 'admin'
  )
);
