-- ==============================================================================
-- MIGRATION: FIX REGISTRATION RLS, AUTO-CREATE PROFILE & APP CONFIG
-- ==============================================================================

-- 1. Create a secure function to handle new user creation from auth
-- ------------------------------------------------------------------------------
-- This runs with SECURITY DEFINER, bypassing RLS, ensuring the profile is ALWAYS created.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (
    id,
    email,
    first_name,
    last_name,
    category,
    sub_category,
    role,
    status,
    photo_url,
    referral_code, -- Will be handled by existing resolve_referral_code trigger
    created_at,
    updated_at,
    is_visible_on_map -- Default false for radar privacy
  )
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'first_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'last_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'category', 'Membre'),
    NEW.raw_user_meta_data->>'sub_category',
    'user',   -- Default role
    'active', -- Auto-activate users as requested ("librement")
    NEW.raw_user_meta_data->>'photo_url',
    NEW.raw_user_meta_data->>'referral_code',
    NOW(),
    NOW(),
    false
  )
  ON CONFLICT (id) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    category = EXCLUDED.category,
    sub_category = EXCLUDED.sub_category,
    email = EXCLUDED.email,
    updated_at = NOW();

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. Attach the trigger to auth.users
-- ------------------------------------------------------------------------------
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 3. Relax RLS Policy for Insert (Double Safety)
-- ------------------------------------------------------------------------------
-- Allow authenticated users to insert their own profile (Standard)
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.users;
CREATE POLICY "Users can insert their own profile"
ON public.users FOR INSERT
WITH CHECK (auth.uid() = id);

-- 4. Allow Updates for Self
-- ------------------------------------------------------------------------------
DROP POLICY IF EXISTS "Users can update their own profile" ON public.users;
CREATE POLICY "Users can update their own profile"
ON public.users FOR UPDATE
USING (auth.uid() = id);

-- 5. SETUP APP CONFIG TABLE (For Admin Messages)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.app_config (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ai_message text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;

-- Allow everyone to READ config
DROP POLICY IF EXISTS "Allow public read access to app_config" ON public.app_config;
CREATE POLICY "Allow public read access to app_config"
ON public.app_config FOR SELECT
USING (true);

-- Allow only admins to UPDATE (Optional - for now open or manual via dashboard)
-- For simplicity in this migration, we ensure the row exists
INSERT INTO public.app_config (id, ai_message)
VALUES (1, 'Bienvenue sur MunokoLive Music !')
ON CONFLICT (id) DO NOTHING;

-- 6. Force Schema Cache Reload
-- ------------------------------------------------------------------------------
NOTIFY pgrst, 'reload schema';
