-- Table pour gérer les sujets de débat dans les salons
CREATE TABLE IF NOT EXISTS public.salon_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id TEXT NOT NULL,
    topic TEXT NOT NULL,
    description TEXT,
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    is_active BOOLEAN DEFAULT true
);

-- Active la sécurité (RLS)
ALTER TABLE public.salon_topics ENABLE ROW LEVEL SECURITY;

-- Politique 1 : Tout le monde peut voir les sujets (Lecture)
CREATE POLICY "Voir les sujets" 
ON public.salon_topics FOR SELECT 
USING (true);

-- Politique 2 : Seuls les admins peuvent créer/modifier (Insert/Update)
-- Note: On simplifie ici en permettant l'insert si l'utilisateur est authentifié, 
-- mais la logique métier (App) vérifiera le rôle admin. 
-- Idéalement, on utiliserait une fonction ou un claim 'role' dans auth.jwt().
CREATE POLICY "Admins gèrent les sujets" 
ON public.salon_topics FOR ALL 
USING (
  auth.uid() IN (
    SELECT id FROM public.users WHERE role IN ('admin', 'super_admin')
  )
);

-- Index pour performance
CREATE INDEX IF NOT EXISTS salon_topics_salon_id_idx ON public.salon_topics (salon_id);
CREATE INDEX IF NOT EXISTS salon_topics_created_at_idx ON public.salon_topics (created_at);

-- Recharger le cache de schéma
NOTIFY pgrst, 'reload schema';
