-- Table pour gérer les adhésions aux salons
CREATE TABLE IF NOT EXISTS public.salon_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    salon_id TEXT NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, salon_id)
);

-- Active la sécurité (RLS)
ALTER TABLE public.salon_memberships ENABLE ROW LEVEL SECURITY;

-- Politique 1 : Tout le monde peut voir les membres (Lecture)
CREATE POLICY "Voir les membres du salon" 
ON public.salon_memberships FOR SELECT 
USING (true);

-- Politique 2 : Les utilisateurs peuvent rejoindre/quitter (Insert/Delete)
CREATE POLICY "Gérer son adhésion" 
ON public.salon_memberships FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Index
CREATE INDEX IF NOT EXISTS salon_memberships_user_id_idx ON public.salon_memberships (user_id);
CREATE INDEX IF NOT EXISTS salon_memberships_salon_id_idx ON public.salon_memberships (salon_id);

-- Recharger le cache
NOTIFY pgrst, 'reload schema';
