-- Ensure chat_messages table exists
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    salon_id TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    user_name TEXT,
    user_avatar TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Ensure salon_memberships table exists
CREATE TABLE IF NOT EXISTS public.salon_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    salon_id TEXT NOT NULL,
    joined_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    last_seen_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(user_id, salon_id)
);

-- Enable RLS
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.salon_memberships ENABLE ROW LEVEL SECURITY;

-- Policies for chat_messages
DROP POLICY IF EXISTS "Public Read Chat" ON public.chat_messages;
CREATE POLICY "Public Read Chat" ON public.chat_messages FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated Insert Chat" ON public.chat_messages;
CREATE POLICY "Authenticated Insert Chat" ON public.chat_messages 
FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Owner Delete Chat" ON public.chat_messages;
CREATE POLICY "Owner Delete Chat" ON public.chat_messages 
FOR DELETE USING (auth.uid() = user_id);

-- Policies for salon_memberships
DROP POLICY IF EXISTS "Public Read Memberships" ON public.salon_memberships;
CREATE POLICY "Public Read Memberships" ON public.salon_memberships FOR SELECT USING (true);

DROP POLICY IF EXISTS "User Manage Membership" ON public.salon_memberships;
CREATE POLICY "User Manage Membership" ON public.salon_memberships 
FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_chat_messages_salon_created ON public.chat_messages (salon_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_salon_memberships_user_salon ON public.salon_memberships (user_id, salon_id);
