-- Création de la table chat_messages qui manque
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    user_name TEXT,
    user_avatar TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Active la sécurité (RLS)
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- Politique 1 : Tout le monde peut lire les messages (Lecture)
CREATE POLICY "Tout le monde peut lire les messages" 
ON public.chat_messages FOR SELECT 
USING (true);

-- Politique 2 : Les utilisateurs connectés peuvent envoyer des messages (Insertion)
CREATE POLICY "Les membres peuvent envoyer des messages" 
ON public.chat_messages FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Politique 3 : Suppression des vieux messages (Nettoyage)
-- Permet à n'importe quel utilisateur connecté de supprimer les messages de plus de 72h
-- (Correspond à votre fonction _cleanupOldMessages)
CREATE POLICY "Nettoyage des vieux messages" 
ON public.chat_messages FOR DELETE 
USING (created_at < (now() - interval '3 days'));

-- Index pour accélérer le chargement et le tri
CREATE INDEX IF NOT EXISTS chat_messages_salon_id_idx ON public.chat_messages (salon_id);
CREATE INDEX IF NOT EXISTS chat_messages_created_at_idx ON public.chat_messages (created_at);

-- Recharger le cache de l'API pour corriger l'erreur PGRST205 immédiatement
NOTIFY pgrst, 'reload schema';
